version: "2"
services:
  brightpod:
    restart: unless-stopped
    build: .
    environment:
      - BP_MQTT_HOST=tcp://localhost:1883
      - BP_MQTT_RUN_SERVER=1
      - BP_MQTT_USERNAME
      - BP_MQTT_PASSWORD
      - BP_MQTT_SERVER_USERS
      - DNSDOCK_ALIAS=brightpod.lxc.ls90
    networks:
      - mediastation
networks:
  mediastation:
    external:
      name: mediastation_ls90
